// flow-typed signature: eb4761b303fc80b4e62c4513b700b147
// flow-typed version: <<STUB>>/babel-preset-es2015-native-generators_v^6.6.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-es2015-native-generators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-es2015-native-generators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-es2015-native-generators/index' {
  declare module.exports: $Exports<'babel-preset-es2015-native-generators'>;
}
declare module 'babel-preset-es2015-native-generators/index.js' {
  declare module.exports: $Exports<'babel-preset-es2015-native-generators'>;
}
